import { createAction } from 'redux-actions'
import { MODULE_NAME } from './models'

export const getFlashSaleProducts = createAction(`${MODULE_NAME}_getFlashSaleProducts`)
export const loadMoreFlashSaleProducts = createAction(`${MODULE_NAME}_loadMoreFlashSaleProducts`)
export const getPopularProducts = createAction(`${MODULE_NAME}_getPopularProducts`)
export const getPopularShops = createAction(`${MODULE_NAME}_getPopularShops`)
export const getNearbyShops = createAction(`${MODULE_NAME}_getNearbyShops`)
export const getDashboardPopularShops = createAction(`${MODULE_NAME}_getDashboardPopularShops`)
export const getDashboardPopularProducts = createAction(`${MODULE_NAME}_getDashboardPopularProducts`)
export const getDashboardNearbyShops = createAction(`${MODULE_NAME}_getDashboardNearbyShops`)
export const loadMorePopularProducts = createAction(`${MODULE_NAME}_loadMorePopularProducts`)
export const loadMorePopularShops = createAction(`${MODULE_NAME}_loadMorePopularShops`)
export const loadMoreNearbyShops = createAction(`${MODULE_NAME}_loadMoreNearbyShops`)
export const getTodayProducts = createAction(`${MODULE_NAME}_getTodayProducts`)
export const getBrandShops = createAction(`${MODULE_NAME}_getBrandShops`)
export const getBrands = createAction(`${MODULE_NAME}_getBrands`)
export const loadMoreBrandShops = createAction(`${MODULE_NAME}_loadMoreBrandShops`)
export const getStyles = createAction(`${MODULE_NAME}_getStyles`)
export const getCategoryProducts = createAction(`${MODULE_NAME}_getCategoryProducts`)
export const getSearchProducts = createAction(`${MODULE_NAME}_getSearchProducts`)
export const loadMoreSearchProducts = createAction(`${MODULE_NAME}_loadMoreSearchProducts`)
export const getSearchShops = createAction(`${MODULE_NAME}_getSearchShops`)
export const loadMoreSearchShops = createAction(`${MODULE_NAME}_loadMoreSearchShops`)
export const getBanners = createAction(`${MODULE_NAME}_getBanners`)
export const getRecommendProducts = createAction(`${MODULE_NAME}_getRecommendProducts`)
export const getVisitedProducts = createAction(`${MODULE_NAME}_getVisitedProducts`)
export const getVisitedShops = createAction(`${MODULE_NAME}_getVisitedShops`)